version: '3.8'
services:
  db:
    image: postgres:14
    networks:
      - my-network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

networks:
  my-network:
    external: true