version: '3.8'
services:
  app:
    build: .
    ports:
      - "9000:9000"
    environment:
      DB_HOST: db
    depends_on:
      - db 
    networks:
      - my-network
    restart: unless-stopped

  db:
    image: postgres:14
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my-network
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

networks:
  my-network:
    external: true

volumes:
  pgdata: